# Generated by Django 4.1.7 on 2023-03-26 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 3, 26, 10, 41, 45, 47677, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title for your blog.", max_length=100),
                ),
                ("text", models.TextField(help_text="Enter your main text here.")),
            ],
            options={
                "ordering": ["date_of_creation"],
            },
        ),
        migrations.CreateModel(
            name="Blogger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nick",
                    models.CharField(
                        help_text="Enter your nickname here", max_length=15
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "date_of_creation",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 3, 26, 10, 41, 45, 47677, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 3, 26, 10, 41, 45, 47677, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.blogger",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.blog"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.blogger",
            ),
        ),
    ]
