# Generated by Django 4.1.7 on 2023-03-26 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_of_creation",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="blogger",
            name="date_of_creation",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comments",
            name="date_of_creation",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
