# Generated by Django 4.1.7 on 2023-03-28 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0003_alter_blog_author_alter_comments_author_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-date_of_creation"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-date_of_creation"]},
        ),
    ]
